default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres5
  password: 1234
  host: localhost
  port: 5432

development:
  <<: *default
  database: web_rails_development

test:
  <<: *default
  database: web_rails_test

production:
  <<: *default
  database: web_rails_production
  username: web_rails
  password: <%= ENV['WEB_RAILS_DATABASE_PASSWORD'] %>
